### ISSUE TITLE
CentOS upstream and baseOS repo no longer working

### ISSUE THREAD

**Issue by edupr91** [isaqueprofeta/zabbix-vagrant#1]
in provision step 

```
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Error: Failed to download metadata for repo 'baseos': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

Fix:
On January 31, 2022, CentOS team has finally [removed](https://www.centos.org/centos-linux-eol/) all packages for CentOS 8 from the official mirrors. CentOS 8 has reached its end-of-life on December 31, 2021, but the packages were kept on the official mirrors for a while. Now they’re moved to https://vault.centos.org/

update repo config
```
sudo sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*
sudo sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*
```

**Comment by isaqueprofeta** [comment]
Thanks a lot for the already answered issue. Wanna send me a pull request? If not, just tell me and I'll update it

**Comment by isaqueprofeta** [comment]
Just removed support for CentOS
